<?php
$me = array('firstname' => 'Jean');
$me['age'] = 39;
$me['favourite_season'] = "Fall";
$me['like_soccer'] = false;
$me['favourite_movies'] = array('300', 'Pearl Harbor', 'Her', 'Interstellar');
$me['hobbies'] = array('gaming', 'read', 'riding');
$my_love = array('firstname' => 'Jeanne');
$my_love['age'] = 39;
$my_love['favourite_season'] = "Fall";
$my_love['like_soccer'] = false;
$my_love['favourite_movies'] = array('300', 'Pearl Harbor', 'Her', 'Interstellar');
$my_love['hobbies'] = array('gaming', 'read');
$me['my_love'] = $my_love;
echo '<pre>';
print_r($me);
echo '</pre>';
echo '<pre>';
echo count($me['my_love']['hobbies']);
echo '</pre>';
echo '<pre>';
echo count($me['hobbies']);
echo '</pre>';
$me['hobbies'][] = 'Taxidermy';
echo '<pre>';
print_r($me['hobbies']);
echo '</pre>';
$me['lastname'] = 'Durand';
$me['firstname'] = 'Jhon';
echo '<pre>';
print_r($me);
echo '</pre>';
$soulmate = array(('hobbies') => array('gaming', 'writing', 'riding', 'painting'));
echo '<pre>';
print_r($soulmate);
echo '</pre>';
$possible_hobbies_via_intersection = array_intersect($me['hobbies'], $soulmate['hobbies']);
$possible_hobbies_via_merge = array_merge($me['hobbies'], $soulmate['hobbies']);
echo '<pre>';
print_r($possible_hobbies_via_intersection);
print_r($possible_hobbies_via_merge);
echo '</pre>';
$web_development = array(('frontend') => [], ('backend') => []);
echo '<pre>';
print_r($web_development);
echo '</pre>';
$web_development['frontend'][] = "xhtml";
echo '<pre>';
print_r($web_development);
echo '</pre>';
$web_development['backend'][] = "Ruby on Rails";
echo '<pre>';
print_r($web_development);
echo '</pre>';
$web_development['frontend'][] = "CSS";
echo '<pre>';
print_r($web_development);
echo '</pre>';
$web_development['backend'][] = "Flash";
echo '<pre>';
print_r($web_development);
echo '</pre>';
$web_development['frontend'][] = "JavaScript";
echo '<pre>';
print_r($web_development);
echo '</pre>';
$web_development['frontend'][0] = "html";
echo '<pre>';
print_r($web_development);
echo '</pre>';
array_splice($web_development['backend'],1,1);
echo '<pre>';
print_r($web_development);
echo '</pre>';
